# Generated by Django 2.2.4 on 2019-08-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='pub_dateeeee',
        ),
    ]
